pipeline:
  name: remoteNonDefaultBranchPipeline
  identifier: remoteNonDefaultBranchPipeline
  projectIdentifier: DoNotDelete_Brooke2
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 'hi, updated file'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
